<?php

use Everyman\Neo4j\Transport,
    Everyman\Neo4j\Client,
    Everyman\Neo4j\Index,
    Everyman\Neo4j\Index\NodeIndex,
    Everyman\Neo4j\Relationship,
    Everyman\Neo4j\Node,
    Everyman\Neo4j\Cypher;

session_start();
header("Content-Type: text/html; charset=utf8");

require_once __DIR__ . '/../../utils/Functions.php';

$events = array();
$tagsss = array();
$tmp=array();

/*
 * Add events
 */
array_push($events, "1000134");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "12");
array_push($tmp, "9");
array_push($tmp, "6");
array_push($tagsss, $tmp);
array_push($events, "1000135");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000136");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "9");
array_push($tagsss, $tmp);
array_push($events, "1000137");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "150");
array_push($tmp, "6");
array_push($tagsss, $tmp);
array_push($events, "1000260");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "31");
array_push($tmp, "125");
array_push($tagsss, $tmp);
array_push($events, "1000107");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "23");
array_push($tagsss, $tmp);
array_push($events, "1000108");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "23");
array_push($tagsss, $tmp);
array_push($events, "1000138");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "150");
array_push($tmp, "1");
array_push($tmp, "2");
array_push($tagsss, $tmp);
array_push($events, "1000139");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "6");
array_push($tmp, "151");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000263");
$tmp=array();
array_push($tmp, "31");
array_push($tagsss, $tmp);
array_push($events, "1000109");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "23");
array_push($tagsss, $tmp);
array_push($events, "1000110");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "23");
array_push($tagsss, $tmp);
array_push($events, "1000131");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000140");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000141");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tagsss, $tmp);
array_push($events, "1000199");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000200");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000201");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000113");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "23");
array_push($tagsss, $tmp);
array_push($events, "1000103");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "125");
array_push($tagsss, $tmp);
array_push($events, "1000114");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "23");
array_push($tagsss, $tmp);
array_push($events, "1000142");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tmp, "2");
array_push($tagsss, $tmp);
array_push($events, "1000143");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000150");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000202");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000203");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000204");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000115");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "23");
array_push($tagsss, $tmp);
array_push($events, "1000116");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "23");
array_push($tagsss, $tmp);
array_push($events, "1000118");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "23");
array_push($tagsss, $tmp);
array_push($events, "1000144");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "149");
array_push($tmp, "1");
array_push($tmp, "2");
array_push($tagsss, $tmp);
array_push($events, "1000145");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "149");
array_push($tagsss, $tmp);
array_push($events, "1000146");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "6");
array_push($tmp, "151");
array_push($tagsss, $tmp);
array_push($events, "1000147");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "6");
array_push($tagsss, $tmp);
array_push($events, "1000148");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000111");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "23");
array_push($tagsss, $tmp);
array_push($events, "1000149");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "9");
array_push($tagsss, $tmp);
array_push($events, "1000264");
$tmp=array();
array_push($tmp, "31");
array_push($tagsss, $tmp);
array_push($events, "1000123");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "5");
array_push($tagsss, $tmp);
array_push($events, "1000152");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "6");
array_push($tmp, "152");
array_push($tagsss, $tmp);
array_push($events, "1000153");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "9");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000154");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "13");
array_push($tmp, "6");
array_push($tagsss, $tmp);
array_push($events, "1000155");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "149");
array_push($tmp, "1");
array_push($tmp, "2");
array_push($tagsss, $tmp);
array_push($events, "1000205");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000206");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000207");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000208");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000209");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000210");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000156");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tmp, "17");
array_push($tmp, "6");
array_push($tmp, "4");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000157");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000158");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "149");
array_push($tmp, "1");
array_push($tmp, "2");
array_push($tagsss, $tmp);
array_push($events, "1000095");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "11");
array_push($tagsss, $tmp);
array_push($events, "1000151");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "149");
array_push($tmp, "2");
array_push($tagsss, $tmp);
array_push($events, "1000091");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "125");
array_push($tmp, "25");
array_push($tagsss, $tmp);
array_push($events, "1000159");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "13");
array_push($tmp, "6");
array_push($tagsss, $tmp);
array_push($events, "1000211");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000212");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000213");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000161");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000261");
$tmp=array();
array_push($tmp, "142");
array_push($tmp, "96");
array_push($tagsss, $tmp);
array_push($events, "1000160");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "149");
array_push($tmp, "2");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000102");
$tmp=array();
array_push($tmp, "113");
array_push($tmp, "106");
array_push($tagsss, $tmp);
array_push($events, "1000214");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000215");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000162");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "151");
array_push($tmp, "2");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000163");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "150");
array_push($tmp, "4");
array_push($tmp, "2");
array_push($tmp, "3");
array_push($tagsss, $tmp);
array_push($events, "1000216");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000265");
$tmp=array();
array_push($tmp, "113");
array_push($tagsss, $tmp);
array_push($events, "1000256");
$tmp=array();
array_push($tmp, "113");
array_push($tmp, "125");
array_push($tmp, "31");
array_push($tagsss, $tmp);
array_push($events, "1000258");
$tmp=array();
array_push($tmp, "113");
array_push($tmp, "125");
array_push($tmp, "31");
array_push($tagsss, $tmp);
array_push($events, "1000262");
$tmp=array();
array_push($tmp, "113");
array_push($tmp, "125");
array_push($tmp, "31");
array_push($tagsss, $tmp);
array_push($events, "1000164");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "149");
array_push($tagsss, $tmp);
array_push($events, "1000165");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "149");
array_push($tmp, "2");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000166");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tagsss, $tmp);
array_push($events, "1000217");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000218");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000219");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000167");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "149");
array_push($tmp, "150");
array_push($tmp, "2");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000168");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000266");
$tmp=array();
array_push($tmp, "113");
array_push($tmp, "75");
array_push($tagsss, $tmp);
array_push($events, "1000169");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "150");
array_push($tmp, "4");
array_push($tmp, "2");
array_push($tmp, "3");
array_push($tagsss, $tmp);
array_push($events, "1000170");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "149");
array_push($tmp, "9");
array_push($tmp, "6");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000171");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "151");
array_push($tmp, "4");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000172");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "151");
array_push($tmp, "4");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000173");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "6");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000220");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000221");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000222");
$tmp=array();
array_push($tmp, "66");
array_push($tmp, "54");
array_push($tagsss, $tmp);
array_push($events, "1000105");
$tmp=array();
array_push($tmp, "113");
array_push($tmp, "109");
array_push($tagsss, $tmp);
array_push($events, "1000174");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "19");
array_push($tmp, "2");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000175");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tmp, "3");
array_push($tagsss, $tmp);
array_push($events, "1000176");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "149");
array_push($tmp, "2");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000177");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000178");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "3");
array_push($tagsss, $tmp);
array_push($events, "1000179");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "9");
array_push($tagsss, $tmp);
array_push($events, "1000180");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "149");
array_push($tmp, "150");
array_push($tmp, "2");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000182");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "150");
array_push($tagsss, $tmp);
array_push($events, "1000181");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "4");
array_push($tmp, "3");
array_push($tagsss, $tmp);
array_push($events, "1000092");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "125");
array_push($tmp, "151");
array_push($tmp, "4");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000254");
$tmp=array();
array_push($tmp, "31");
array_push($tmp, "125");
array_push($tmp, "113");
array_push($tagsss, $tmp);
array_push($events, "1000183");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "149");
array_push($tmp, "6");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000184");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000185");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "6");
array_push($tmp, "151");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000186");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000187");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "13");
array_push($tmp, "12");
array_push($tmp, "150");
array_push($tmp, "6");
array_push($tmp, "2");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000188");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "151");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000192");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "9");
array_push($tagsss, $tmp);
array_push($events, "1000101");
$tmp=array();
array_push($tmp, "113");
array_push($tmp, "132");
array_push($tagsss, $tmp);
array_push($events, "1000189");
$tmp=array();
array_push($tmp, "10");
array_push($tagsss, $tmp);
array_push($events, "1000193");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "9");
array_push($tmp, "6");
array_push($tagsss, $tmp);
array_push($events, "1000190");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "6");
array_push($tmp, "152");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000191");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "149");
array_push($tmp, "4");
array_push($tmp, "3");
array_push($tagsss, $tmp);
array_push($events, "1000194");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000195");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "150");
array_push($tmp, "2");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000196");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "17");
array_push($tmp, "2");
array_push($tmp, "1");
array_push($tagsss, $tmp);
array_push($events, "1000197");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
array_push($events, "1000198");
$tmp=array();
array_push($tmp, "10");
array_push($tmp, "4");
array_push($tagsss, $tmp);
/*
 * Add events
 */
$i = 0;
if (!empty($events) && sizeof($events) > 0) {
    foreach ($events as $evtId) {
        if (!empty($evtId)) {
            $event = Neo4jEventUtils::getEventNode($evtId);
            if (!empty($event)) {
                $id = $event->getProperty(PROP_EVENT_ID);
                if (!empty($id)) {
                    $tags = $tagsss[$i];
                    if (!empty($tags) && sizeof($tags) > 0) {
                        foreach ($tags as $tagId) {
                            if (!empty($tagId)) {
                                $tag = Neo4jTimetyTagUtil::getTimetyTagNodeById($tagId,LANG_TR_TR);
                                $tag = Neo4jTimetyTagUtil::getTimetyTagNodeById($tagId,LANG_EN_US);
                                if (!empty($tag)) {
                                    $tId = $tag->getProperty(PROP_TIMETY_TAG_ID);
                                    if (!empty($tId)) {
                                        $tag->relateTo($event, REL_TAGS)->save();
                                    }
                                }
                            }
                        }
                    }
                }
            }
            $i++;
        }
    }
}
?>
