var TIMETY_SUBFOLDER='/timety/';
var TIMETY_HOSTNAME='http://'+window.location.hostname+TIMETY_SUBFOLDER;
var TIMETY_HOSTNAME_WWW='http://'+window.location.hostname+TIMETY_SUBFOLDER;

var TIMETY_PAGE_AJAX_SESSION=TIMETY_HOSTNAME+'session.php';

var TIMETY_PAGE_ABOUT_YOU=TIMETY_HOSTNAME+'about-you';
var TIMETY_PAGE_EVENT_DETAIL=TIMETY_HOSTNAME+'event/';

var TIMETY_PAGE_SOCIAL_FB_LOGIN=TIMETY_HOSTNAME+'login-facebook.php';
var TIMETY_PAGE_SOCIAL_FQ_LOGIN=TIMETY_HOSTNAME+'login-foursquare.php';
var TIMETY_PAGE_SOCIAL_TW_LOGIN=TIMETY_HOSTNAME+'login-twitter.php';

var TIMETY_AJAX_FOLDER=TIMETY_HOSTNAME+'ajax/';
var TIMETY_PAGE_AJAX_CHECKUSERNAME=TIMETY_AJAX_FOLDER+'checkUserName.php';
var TIMETY_PAGE_AJAX_CHECKEMAIL=TIMETY_AJAX_FOLDER+'checkEmail.php';
var TIMETY_PAGE_AJAX_GETCATEGORYTOKEN=TIMETY_AJAX_FOLDER+'getCategoryToken.php';
var TIMETY_PAGE_AJAX_UNFOLLOWUSER=TIMETY_AJAX_FOLDER+'unfollowUser.php';
var TIMETY_PAGE_AJAX_FOLLOWUSER=TIMETY_AJAX_FOLDER+'followUser.php';
var TIMETY_PAGE_AJAX_CHECKINTERESTREADY=TIMETY_AJAX_FOLDER+'checkInterestReady.php';
var TIMETY_PAGE_AJAX_INVITEEMAIL=TIMETY_AJAX_FOLDER+'inviteEmail.php';
var TIMETY_PAGE_AJAX_CHECKGROUPNAME=TIMETY_AJAX_FOLDER+'checkGroupName.php';
var TIMETY_PAGE_AJAX_RESPONSETOGROUPINVITES=TIMETY_AJAX_FOLDER+'responseToGroupInvites.php';
var TIMETY_PAGE_AJAX_JOINEVENT=TIMETY_AJAX_FOLDER+'joinEvent.php';
var TIMETY_PAGE_AJAX_RESPONSETOEVENTINVITES=TIMETY_AJAX_FOLDER+'responseToEventInvites.php';
var TIMETY_PAGE_AJAX_GETEVENTATTENDANCES=TIMETY_AJAX_FOLDER+'getEventAttendances.php';
var TIMETY_PAGE_AJAX_GETCOMMENTS=TIMETY_AJAX_FOLDER+'getComments.php';
var TIMETY_PAGE_AJAX_ADDCOMMENTS=TIMETY_AJAX_FOLDER+'addComment.php';
var TIMETY_PAGE_AJAX_GETEVENTS=TIMETY_AJAX_FOLDER+'getEvents.php';
var TIMETY_PAGE_AJAX_UPLOADIMAGE=TIMETY_AJAX_FOLDER+'uploadImage.php';
var TIMETY_PAGE_AJAX_GETCATEGORY=TIMETY_AJAX_FOLDER+'getCategory.php';
var TIMETY_PAGE_AJAX_GETTAG=TIMETY_AJAX_FOLDER+'getTag.php';
var TIMETY_PAGE_AJAX_GETPEOPLEORGROUP=TIMETY_AJAX_FOLDER+'getPeopleOrGroup.php';
var TIMETY_PAGE_AJAX_GETEVENT=TIMETY_AJAX_FOLDER+'getEvent.php';
var TIMETY_PAGE_AJAX_GETNOTFCOUNT=TIMETY_AJAX_FOLDER+'getNotificationsCount.php';
var TIMETY_PAGE_AJAX_GETNOTF=TIMETY_AJAX_FOLDER+'getNotifications.php';
var TIMETY_PAGE_AJAX_GETUSERSUBSCRIBES=TIMETY_AJAX_FOLDER+'getUserSubscribes.php';
var TIMETY_PAGE_AJAX_SUBSCRIBEUSER=TIMETY_AJAX_FOLDER+'subscribeUser.php';
var TIMETY_PAGE_AJAX_UNSUBSCRIBEUSER=TIMETY_AJAX_FOLDER+'unsubscribeUser.php';
var TIMETY_PAGE_AJAX_GETFRIENDS=TIMETY_AJAX_FOLDER+'getFriends.php';



