<?php 
define('FQ_CLIENT_ID', 'VVCL10IOM4GR5NTSPATFNSGKT1GH50GINKW2D5JFBFQBORQ0');
define('FQ_CLIENT_SECRET', 'IS1BFQYC2WWNE42VYTGJ4G5JPL5HCVSLLFSRJMYVFDKYMRTS');
//define('FQ_CLIENT_ID', 'JSKSQQKFUVIOUHBLRGK0G3TDUPQQRUX3HKNUMNNVQY1K3ZN2');
//define('FQ_CLIENT_SECRET', 'SP2OW1VZ0DJN0OTC42SY5RGTAKUCPWIGQATZTRXM4JO1RFEP');

define('FQ_CALLBACK_URL','getFoursquareUser.php');
?>